### ISSUE TITLE
SciterWindow.Title cannot be set.

### ISSUE THREAD

**Issue by stuffinator** [MISoftware/SciterSharp#10]
When trying to set the title of a SciterWindow nothing happens. The "Title"-property stays an empty string.

![grafik](https://user-images.githubusercontent.com/26797810/40278543-e9d06e90-5c32-11e8-9f45-95e6bf7fd7e1.png)

I'm using the current nuget-Version 2.0.55 and I'm only running the windows project (no GTK or OSX) and I'm using .Net Framework 4.7.1 (although I also tried 4.5.2).

Setting any other property works fine.

**Comment by midiway** [comment]
You must create the window before setting its Title:

```
var wnd = new SciterWindow();
wnd.CreateMainWindow(1500, 800);
wnd.CenterTopLevelWindow();
wnd.Title = "TestCore";
```

**Comment by stuffinator** [comment]
Well look at that, it works. I feel a tiny bit stupid now.

Thanks mate.
