### ISSUE TITLE
Tabs sample

### ISSUE THREAD

**Issue by TumanovaOlga** [MISoftware/SciterSharp#12]
Could you explain why sciter-sdk\samples\behaviors\tabs.htm doesn't work correcty in Omni browser or using SciterSharp while sciter.exe shows them correctly? Is it a bug?

**Comment by midiway** [comment]
Because this depends on a native behavior from Sciter SDK: \sciter-sdk\include\behaviors\behavior_tabs.cpp
...which I did not implemented in C#

What you could is check the C++ implemention of the behavior and do it all in TIScript

**Comment by TumanovaOlga** [comment]
Ok. Thanks for the response
