### ISSUE TITLE
Most efficient way to transfer int[]

### ISSUE THREAD

**Issue by nxrighthere** [MISoftware/SciterSharp#13]
I wonder, what is the most efficient/performance-friendly way to transfer an array of int values (20 entries) C# -> tiscript? I'm currently thinking about to convert the int array into the byte array and decode it, but this operation is going to happen every 16 ms, and I'm not sure if this is the best way to do this.

Any advice please?

**Comment by midiway** [comment]
You can create a SciterValue from a int[] with [SciterValue.FromList](https://github.com/MISoftware/SciterSharp/blob/master/SciterSharp/SciterValue.cs#L236) method

That is, you are actually constructing a TIScript array from C#.

**Comment by nxrighthere** [comment]
Oh, thank you. It seems that I overcomplicate things a bit.
