### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Carlos487** [MISoftware/SciterSharp#6]
I have a doubt regarding the license of SciterSharp, given that your license is GPL you could not use it in commercial applications without making it open source. Is it that correct? Because I consider that can impact the growth of this tool.

Best regards

**Comment by midiway** [comment]
If you making a commercial product, then you need a commercial license, see #1 and #2 
If you are making an Open-source software where GPL doesn't fits, I can make an exception, just tell me more about it
