### ISSUE TITLE
How to use it with OpenTK or MonoGame ?

### ISSUE THREAD

**Issue by RUSshy** [MISoftware/SciterSharp#8]
Hello

Im try to figure out how to get get the data in order to use it with opengl or monogame

Is it like CEF ? Can you point me in right direction please ?

Ty!

**Comment by midiway** [comment]
Yes, it is like CEF, but much more powerfull IMHO: more optimized for desktop apps, less CPU/memory usage.

Theorically you can integrate it with any DirectX or OpenGL graphics backend, but I have never done. What there is this two demos found in the SDK:
- https://sciter.com/sciter-and-directx/
- https://sciter.com/sciter-and-opengl/

For getting started, check my tutorial: www.codeproject.com/Articles/1057199/Sciter-HTML-Csharp-based-desktop-apps-walkthrough

**Comment by RUSshy** [comment]
I checked already source from SDK with opengl example, but i don't know c++ enough to understand what is going on :/

**Comment by RUSshy** [comment]
I tried this with sfml c# https://gist.github.com/RUSshy/fccea8dbf2680e456b5b4e9a619ccef3#file-test-cs-L44

But it refuse to load the page

**Comment by midiway** [comment]
Well, you would have to translate the SFML C++  sample (sdk/demos.GLFW/sciter-glfw-basic) to C#, shouldn't be so hard.
I can't really help with that (sorry, no time available).
You should be asking for help on the [forum](https://sciter.com/forums/), Andrew is more suited for helping in this area.

You should first understand what is the Sciter API function that draws the HTML page on top of SFML. Ask it on the forum...

**Comment by RUSshy** [comment]
Ok i'll try on forum, ty! 

If solution found would be nice to have in samples for other people

**Comment by RUSshy** [comment]
Can you write sample for this part in c++ to c# to get the draw data ?

```
// SCITER 
{
      SCITER_X_MSG_PAINT pc(back_layer,FALSE);
      pc.targetType = SPT_RECEIVER;
      pc.target.receiver.callback = BackElementBitmapReceiver;
      pc.target.receiver.param = 0;
      SciterProcX(hwnd(window), pc);
}
```

**Comment by RUSshy** [comment]
I tried ask on forum but no luck :/

I give up for the moment, i hope one day u can write tutorial for using it with monogame or sfml or something else
